# Site settings
title: RIS Tutorials
institute: Minnesota Supercomputing Institute
univeristy: University of Minnesota
description: Tutorials hosted and developed by RIS at MSI
future: true
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
